"""Domains, mailboxes and aliases — Micronet Solutions internal mail platform.

Postfix and Dovecot query these tables directly via read-only SQL maps
(see compose/postfix/pgsql-*.cf and compose/dovecot/dovecot-sql.conf.ext),
so creating a Mailbox row makes the address live immediately.

NOTE: No external billing/SaaS. This is an internal-only platform for
Micronet Solutions and its sister companies.
"""
import secrets
from django.conf import settings
from django.db import models
from django.utils import timezone


class SubscriptionTier(models.TextChoices):
    FREE = "free", "Free"
    STARTER = "starter", "Starter"
    PRO = "pro", "Pro"


class Organization(models.Model):
    """Represents Micronet Solutions or one of its sister companies."""
    name = models.CharField(max_length=255)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="owned_organizations"
    )
    members = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="organizations",
        blank=True
    )
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    # Billing & Subscription fields (Mocked for internal use)
    stripe_customer_id = models.CharField(max_length=255, blank=True, null=True)
    stripe_subscription_id = models.CharField(max_length=255, blank=True, null=True)
    tier = models.CharField(
        max_length=20,
        choices=SubscriptionTier.choices,
        default=SubscriptionTier.PRO,
    )
    subscription_status = models.CharField(max_length=50, default="active")

    def __str__(self) -> str:
        return self.name


class Domain(models.Model):
    organization = models.ForeignKey(
        Organization,
        on_delete=models.CASCADE,
        related_name="domains",
        null=True,
        blank=True
    )
    name = models.CharField(max_length=255, unique=True)
    dkim_selector = models.CharField(max_length=63, default="mail")
    active = models.BooleanField(default=False)

    # DNS Verification details
    verification_token = models.CharField(max_length=64, blank=True, unique=True)
    is_verified = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name

    def save(self, *args, **kwargs):
        if not self.verification_token:
            self.verification_token = secrets.token_hex(32)
        super().save(*args, **kwargs)


class Mailbox(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="mailboxes"
    )
    domain = models.ForeignKey(Domain, on_delete=models.PROTECT)
    local_part = models.CharField(max_length=64)
    # Dovecot-compatible hash with scheme prefix, e.g. "{ARGON2ID}$argon2id$...".
    # Generated by accounts.services.dovecot_hash(); never store plaintext.
    password_hash = models.CharField(max_length=512)
    maildir_path = models.CharField(max_length=512, editable=False)
    quota_mb = models.PositiveIntegerField(default=2048)
    active = models.BooleanField(default=True)
    avatar = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("domain", "local_part")
        verbose_name_plural = "mailboxes"

    @property
    def address(self) -> str:
        return f"{self.local_part}@{self.domain.name}"

    def save(self, *args, **kwargs):
        if not self.maildir_path:
            self.maildir_path = f"/var/vmail/{self.domain.name}/{self.local_part}/"
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.address


class Alias(models.Model):
    domain = models.ForeignKey(Domain, on_delete=models.CASCADE)
    # source="" means catch-all for the domain.
    source = models.CharField(max_length=64, blank=True)
    destination = models.EmailField()
    active = models.BooleanField(default=True)

    class Meta:
        unique_together = ("domain", "source", "destination")
        verbose_name_plural = "aliases"

    def __str__(self) -> str:
        src = self.source or "*"
        return f"{src}@{self.domain.name} -> {self.destination}"


class AppPassword(models.Model):
    """Per-device passwords for IMAP clients when the account uses 2FA."""
    mailbox = models.ForeignKey(Mailbox, on_delete=models.CASCADE, related_name="app_passwords")
    label = models.CharField(max_length=64)  # "Phone", "Thunderbird", ...
    password_hash = models.CharField(max_length=512)
    created_at = models.DateTimeField(auto_now_add=True)
    last_used_at = models.DateTimeField(null=True, blank=True)


class MailboxStatusLog(models.Model):
    mailbox_id = models.PositiveIntegerField()
    mailbox_address = models.CharField(max_length=255)
    organization = models.ForeignKey(
        Organization,
        on_delete=models.CASCADE,
        related_name="mailbox_status_logs"
    )
    active = models.BooleanField()
    changed_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ["changed_at"]
        indexes = [
            models.Index(fields=["mailbox_id", "changed_at"]),
            models.Index(fields=["organization", "changed_at"]),
        ]

    def __str__(self) -> str:
        status_str = "Active" if self.active else "Inactive"
        return f"{self.mailbox_address} -> {status_str} at {self.changed_at}"


from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

@receiver(post_save, sender=Mailbox)
def log_mailbox_save(sender, instance, created, **kwargs):
    if not instance.domain.organization:
        return
    write_log = False
    if created:
        write_log = True
    else:
        last_log = MailboxStatusLog.objects.filter(mailbox_id=instance.id).order_by("-changed_at").first()
        if not last_log or last_log.active != instance.active:
            write_log = True

    if write_log:
        MailboxStatusLog.objects.create(
            mailbox_id=instance.id,
            mailbox_address=instance.address,
            organization=instance.domain.organization,
            active=instance.active
        )


@receiver(post_delete, sender=Mailbox)
def log_mailbox_delete(sender, instance, **kwargs):
    if not instance.domain.organization:
        return
    MailboxStatusLog.objects.create(
        mailbox_id=instance.id,
        mailbox_address=instance.address,
        organization=instance.domain.organization,
        active=False
    )
