# Generated by Django 5.2.15 on 2026-06-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0003_backfill_conversation_id"),
    ]

    operations = [
    ]
