# Generated by Django 5.2.15 on 2026-06-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0003_backfill_conversation_id"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="messagemeta",
            new_name="mail_messag_search__5af681_gin",
            old_name="mail_messag_search__205b38_gin",
        ),
        migrations.RenameIndex(
            model_name="messagemeta",
            new_name="mail_messag_mailbox_5a4d34_idx",
            old_name="mail_messag_mailbox_82e88a_idx",
        ),
    ]
